services:
  flask:
    image: blinn/prosusai-finbert:latest
    ports:
      - 5000:5000
    restart: always

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    #volumes:
    #  - ./proxy.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - flask